<a href="https://colab.research.google.com/github/fbtkdqo/2020-2-AI/blob/master/code/03-tf-manip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.3.0'

In [2]:
a = 2
b = 3
c = tf.add(a, b)
print(c.numpy())

5


In [3]:
x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
pow_op = tf.pow(add_op, mul_op)

print(pow_op.numpy())

15625


In [4]:
a = tf.constant(2.)
b = tf.constant(3.)
c = tf.constant(5.)

# Some more operations.
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print("mean = ", mean.numpy())
print("sum = ", sum.numpy())

mean =  3.3333333
sum =  10.0


In [5]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[2., 0.], [1., 2.]])

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

gop = tf.matmul(matrix2, matrix1)
print(gop.numpy())

[[ 4.  4.]
 [10.  8.]]
[[ 2.  4.]
 [ 7. 10.]]


Tensor Manipulation

In [6]:
import pprint

pp = pprint.PrettyPrinter(indent=4)
print(tf.__version__)

2.3.0


Simple Array

In [7]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


2D Array

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


Shape, Rank, Axis

In [9]:
t = tf.constant([1,2,3,4])
tf.shape(t).numpy()

array([4], dtype=int32)

In [10]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).numpy()

array([2, 2], dtype=int32)

In [11]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t)
tf.shape(t).numpy()

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)


array([1, 2, 3, 4], dtype=int32)

In [12]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

Matmul VS multiply

In [13]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).numpy()

array([[12.]], dtype=float32)

In [14]:
(matrix1 * matrix2).numpy()

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [15]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1 + matrix2).numpy()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [16]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).numpy()

array([[5., 5.]], dtype=float32)

In [17]:
tf.random.normal([3]).numpy()

array([ 1.8601309, -0.535251 , -1.5787617], dtype=float32)

In [18]:
tf.random.uniform([2]).numpy()

array([0.5743072 , 0.30852902], dtype=float32)

In [19]:
tf.random.uniform([2, 3]).numpy()

array([[0.06730056, 0.52896917, 0.62806976],
       [0.8255532 , 0.34366035, 0.476897  ]], dtype=float32)

In [20]:
tf.reduce_mean([1, 2], axis=0).numpy()

1

In [21]:
tf.reduce_mean([1., 2.], axis=0).numpy()

1.5

In [22]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).numpy()

2.5

In [23]:
tf.reduce_mean(x, axis=0).numpy()

array([2., 3.], dtype=float32)

In [24]:
tf.reduce_mean(x, axis=1).numpy()

array([1.5, 3.5], dtype=float32)

In [25]:
tf.reduce_mean(x, axis=-1).numpy()

array([1.5, 3.5], dtype=float32)

In [26]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_sum(x).numpy()

10.0

In [27]:
tf.reduce_sum(x, axis=0).numpy()

array([4., 6.], dtype=float32)

In [28]:
tf.reduce_sum(x, axis=1).numpy()

array([3., 7.], dtype=float32)

In [29]:
tf.reduce_sum(x, axis=-1).numpy()

array([3., 7.], dtype=float32)

In [30]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).numpy()

5.0

In [31]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).numpy()

array([1, 0, 0])

In [32]:
tf.argmax(x, axis=1).numpy()

array([2, 0])

In [33]:
tf.argmax(x, axis=-1).numpy()

array([2, 0])

In [34]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [35]:
tf.reshape(t, shape=[-1, 3]).numpy()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
tf.reshape(t, shape=[-1, 1, 3]).numpy()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [37]:
a = np.array([[0], [1], [2]])
print(a.shape)
b = tf.squeeze(a)
print(b.shape)
b.numpy()

(3, 1)
(3,)


array([0, 1, 2])

In [38]:
a = np.array([[[0, 1], [2, 3]]])
print(a.shape)
b = tf.squeeze(a)
print(b.shape)
b.numpy()

(1, 2, 2)
(2, 2)


array([[0, 1],
       [2, 3]])

In [39]:
a = np.array([[[0, 1]], [[2, 3]]])
print(a.shape)
b = tf.squeeze(a)
print(b.shape)
b.numpy()

(2, 1, 2)
(2, 2)


array([[0, 1],
       [2, 3]])

In [40]:
a = np.array([0, 1, 2])
print(a.shape)
b = tf.expand_dims(a, 0)
print(b.shape)
b.numpy()

(3,)
(1, 3)


array([[0, 1, 2]])

In [41]:
a = np.array([0, 1, 2])
print(a.shape)
b = tf.expand_dims(a, 1)
print(b.shape)
b.numpy()

(3,)
(3, 1)


array([[0],
       [1],
       [2]])

In [42]:
# 차수가 하나 늘어나며, depth는 유형 종류의 수
tf.one_hot([[0], [1], [2], [0]], depth=3).numpy()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [43]:
# 차수가 하나 늘어나며, depth는 유형 종류의 수
tf.one_hot([[0], [1], [2], [0]], depth=2).numpy()

array([[[1., 0.]],

       [[0., 1.]],

       [[0., 0.]],

       [[1., 0.]]], dtype=float32)

In [44]:
tf.one_hot([[0], [1], [2], [0]], depth=4).numpy()

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[1., 0., 0., 0.]]], dtype=float32)

In [45]:
tf.one_hot([[0], [1], [2], [0]], depth=5).numpy()

array([[[1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0.]],

       [[0., 0., 1., 0., 0.]],

       [[1., 0., 0., 0., 0.]]], dtype=float32)

In [46]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print(t.numpy())
tf.reshape(t, shape=[-1, 3]).numpy()

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [47]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print(t.numpy())
tf.squeeze(t).numpy()

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [48]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy()

array([1, 2, 3, 4], dtype=int32)

In [49]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).numpy()

array([1, 0, 1, 0], dtype=int32)

In [50]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).numpy()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [51]:
tf.stack([x, y, z], axis=1).numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [52]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).numpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [53]:
tf.zeros_like(x).numpy()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [54]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [55]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


In [56]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [57]:
t1 = tf.transpose(t, [0, 1, 2])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>


In [58]:
t1 = tf.transpose(t, [0, 2, 1])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 3, 2])
<tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])>


In [59]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])>


In [60]:
t1 = tf.transpose(t, [1, 2, 0])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 3, 2])
<tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])>


In [61]:
t1 = tf.transpose(t, [2, 0, 1])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([3, 2, 2])
<tf.Tensor: shape=(3, 2, 2), dtype=int64, numpy=
array([[[ 0,  3],
        [ 6,  9]],

       [[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]]])>


In [62]:
t1 = tf.transpose(t, [2, 1, 0])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([3, 2, 2])
<tf.Tensor: shape=(3, 2, 2), dtype=int64, numpy=
array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])>
